package com.adminremit.auth.enums;

public enum FeatureType {
    USER_CREATE,USER_EDIT,USER_VIEW,USER_DELETE,
    GROUP_CREATE,GROUP_EDIT,GROUP_VIEW,GROUP_DELETE,
        ROLES_EDIT,ROLES_VIEW,ROLES_DELETE,ROLES_CREATE,
    PAYMODE_EDIT,PAYMODE_VIEW,PAYMODE_DELETE,PAYMODE_CREATE,
    RECEIVEMODE_EDIT,RECEIVEMODE_VIEW,RECEIVEMODE_DELETE,RECEIVEMODE_CREATE,
    FEE_EDIT,FEE_VIEW,FEE_DELETE,FEE_CREATE,FEE_APPROVE,
    GLOBAL_EDIT,GLOBAL_VIEW,GLOBAL_DELETE,GLOBAL_CREATE,GLOBAL_APPROVE,
    SERVICE_EDIT,SERVICE_VIEW,SERVICE_DELETE,SERVICE_CREATE,SERVICE_APPROVE,
    MARGIN_EDIT,MARGIN_VIEW,MARGIN_DELETE,MARGIN_CREATE,MARGIN_APPROVE,
    FILE_UPLOAD_VIEW, FILE_UPLOAD_ADD, FILE_UPLOAD_APPROVE,FILE_UPLOAD_DELETE,FILE_UPLOAD_EDIT,
    TAT_EDIT, TAT_VIEW, TAT_DELETE, TAT_CREATE, TAT_APPROVE, HOLIDAY_EDIT, HOLIDAY_VIEW, HOLIDAY_DELETE, HOLIDAY_CREATE, HOLIDAY_APPROVE,

    BACK_OFFICE_STAGING_EDIT, BACK_OFFICE_STAGING_VIEW, BACK_OFFICE_STAGING_DELETE, BACK_OFFICE_STAGING_CREATE, BACK_OFFICE_STAGING_APPROVE,
    BACK_OFFICE_RETURNS_EDIT, BACK_OFFICE_RETURNS_VIEW, BACK_OFFICE_RETURNS_DELETE, BACK_OFFICE_RETURNS_CREATE, BACK_OFFICE_RETURNS_APPROVE,
    BACK_OFFICE_REFUND_EDIT, BACK_OFFICE_REFUND_VIEW, BACK_OFFICE_REFUND_DELETE, BACK_OFFICE_REFUND_CREATE, BACK_OFFICE_REFUND_APPROVE,
    BACK_OFFICE_DISBURSEMENT_EDIT, BACK_OFFICE_DISBURSEMENT_VIEW, BACK_OFFICE_DISBURSEMENT_DELETE, BACK_OFFICE_DISBURSEMENT_CREATE,
    BACK_OFFICE_DISBURSEMENT_APPROVE, BACK_OFFICE_BACK_OFFICE_FILE_UPLOAD_EDIT, BACK_OFFICE_BACK_OFFICE_FILE_UPLOAD_VIEW,
    BACK_OFFICE_BACK_OFFICE_FILE_UPLOAD_DELETE, BACK_OFFICE_BACK_OFFICE_FILE_UPLOAD_CREATE, BACK_OFFICE_BACK_OFFICE_FILE_UPLOAD_APPROVE,

    COMPLIANCE_EDIT, COMPLIANCE_VIEW, COMPLIANCE_DELETE, COMPLIANCE_CREATE, COMPLIANCE_APPROVE, COMPLIANCE_FILE_UPLOAD_EDIT,
    COMPLIANCE_FILE_UPLOAD_VIEW, COMPLIANCE_FILE_UPLOAD_DELETE, COMPLIANCE_FILE_UPLOAD_CREATE, COMPLIANCE_FILE_UPLOAD_APPROVE,
    RECONCILIATION_UNMATCHED_EDIT, RECONCILIATION_UNMATCHED_VIEW, RECONCILIATION_UNMATCHED_DELETE, RECONCILIATION_UNMATCHED_CREATE,
    RECONCILIATION_UNMATCHED_APPROVE, RECONCILIATION_MATCHED_EDIT, RECONCILIATION_MATCHED_VIEW, RECONCILIATION_MATCHED_DELETE,
    RECONCILIATION_MATCHED_CREATE, RECONCILIATION_MATCHED_APPROVE, REGISTRATION_REPORT_VIEW, RECIPIENT_REPORT_VIEW, REMITTER_SUMMARY_VIEW,
    TRANSACTION_REPORT_VIEW, TRANSACTION_SUMMARY_VIEW, RECONCILIATION_REPORT_VIEW,COMPLIANCE_CHECKLIST_VIEW,BUSINESS_REGISTRATION_SUMMARY_REPORT_VIEW
}
