package com.adminremit.auth.enums;

public enum FunctionMasterKey {
    USER_MANAGEMENT,GROUP_MODIFY,ROLES_MODIFY,
    PAYMENT_MODE_MODIFY,RECEIVE_MODE_MODIFY,FEE_MODIFY,FEE_APPROVE,
    GLOBAL_LIMITS,GLOBAL_LIMITS_APPROVE,SERVICE_CHARGE_MODIFY,SERVICE_CHARGE_APPROVE,
    MARGIN_MODIFY,MARGIN_APPROVE, FILE_UPLOAD,TAT_MODIFY,HOLIDAY_MODIFY,BACK_OFFICE_STAGING,
    BACK_OFFICE_RETURNS,
    BACK_OFFICE_REFUND,
    BACK_OFFICE_DISBURSEMENT,
    BACK_OFFICE_FILE_UPLOAD,
    COMPLIANCE,
    COMPLIANCE_FILE_UPLOAD,
    RECONCILIATION_UNMATCHED,
    RECONCILIATION_MATCHED,
    REGISTRATION_REPORT,
    RECIPIENT_REPORT,
    REMITTER_SUMMARY,
    TRANSACTION_REPORT,
    TRANSACTION_SUMMARY,
    RECONCILIATION_REPORT,
    COMPLIANCE_CHECKLIST,
    BUSINESS_REGISTRATION_SUMMARY_REPORT
}
