package com.adminremit.operations.model;

public enum WorkflowStatus {
    CONFIRMED,
    CANCEL,
    BACKOFFICE_CANCEL,
    BACKOFFICE_CANCEL_CONFIRMED,
    STAGING_START,
    STAGING_COMPLETED,
    STAGING_CANCELLED,
    MATCHED_EXCEPTION,
    MATCHED_EXCEPTION_CHECKER,
    UNMATCHED_ENTRIES,
    COMPLIANCE_START,
    DISBURSEMENT_START,
    DISBURSEMENT_CHECK,
    SENT_TO_BANK,
    CANCELLED_BY_USER,
    REFUND_START,
    CANCELLED,
    COMPLETED,
    SENT_TO_BENEFICIARY
 }