package com.adminremit.operations.model;

public enum WorkflowStatusNames {
    CONFIRMED("CONFIRMED"),
    CANCEL("CANCEL"),
    BACKOFFICE_CANCEL("BACKOFFICE CANCEL"),
    BACKOFFICE_CANCEL_CONFIRMED("BACKOFFICE CANCEL CONFIRMED"),
    STAGING_START("STAGING START"),
    STAGING_COMPLETED("STAGING COMPLETED"),
    STAGING_CANCELLED("STAGING CANCELLED"),
    MATCHED_EXCEPTION("MATCHED EXCEPTION"),
    MATCHED_EXCEPTION_CHECKER("MATCHED EXCEPTION CHECKER"),
    UNMATCHED_ENTRIES("UNMATCHED ENTRIES"),
    COMPLIANCE_START("COMPLIANCE START"),
    DISBURSEMENT_START("DISBURSEMENT START"),
    DISBURSEMENT_CHECK("DISBURSEMENT CHECK"),
    SENT_TO_BANK("SENT TO BANK"),
    CANCELLED_BY_USER("CANCELLED BY USER"),
    REFUND_START("REFUND START"),
    CANCELLED("CANCELLED"),
    COMPLETED("COMPLETED"),
    SENT_TO_BENEFICIARY("SENT TO BENEFICIARY");
    
    private final String name;

    private WorkflowStatusNames(String name) {
        this.name = name;
    }

	public String getName() {
		return name;
	}	
 }