#security.basic.enabled=false
server.port=8090
server.ssl.enabled=true
server.ssl.client-auth=want
server.ssl.key-store=classpath:remzit_crt.jks
server.ssl.key-store-password=Admin@123
server.ssl.key-alias=remzit
server.ssl.key-store-type=JKS
server.ssl.key-store-provider=SUN
server.ssl.trust-store=classpath:sky.yesbank.in_Main.jks
server.ssl.trust-store-password=Admin@123
server.ssl.trust-store-type=JKS

#Sprign session saving to redis
spring.session.store-type=redis
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
server.servlet.session.timeout=100000
spring.session.redis.flush-mode=on-save
spring.session.redis.namespace=spring:session
spring.data.redis.repositories.enabled = false
spring.cache.redis.cache-null-values=false

# Onfido Configuration (set ONFIDO_LIVE_TOKEN in env; see .env.example)
onfido.token=${ONFIDO_LIVE_TOKEN}
onfido.referrer=https://xdcforpayments.org/
onfido.sdk.url=https://api.onfido.com/v3/sdk_token

#Liquibase
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
logging.level.liquibase = INFO

#Posgres config
#spring.datasource.url=jdbc:postgresql://prod-db-instance.cfm9mcxeqe9z.ap-southeast-2.rds.amazonaws.com:5432/remittances
#spring.datasource.url=jdbc:postgresql://prod-db-instance.cfm9mcxeqe9z.ap-southeast-2.rds.amazonaws.com:5432/prodremittances
#spring.datasource.username=postgres
#spring.datasource.password=AndRemit#234

spring.datasource.url=jdbc:postgresql://localhost:5432/prodremittances
spring.datasource.username=postgres
spring.datasource.password=AndRemit#234

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

#Default super admin creation
admin.andremit.firstname=Admin
admin.andremit.lastname=Andremit

admin.andremit.username=superadmin
admin.andremit.password=$uper@dmin#123

admin.andremit.default.role=SUPERADMIN
admin.partner.name=Andremit
admin.product.name=Andremit
admin.group.name=Super Admin Group

reset.password.url=https://admin.remzit.com:8090/reset/password/

spring.main.banner-mode=off

org.hibernate.envers.audit_table_prefix = audit
org.hibernate.envers.audit_table_suffix =
org.hibernate.envers.revision_on_collection_change = false

management.endpoints.web.exposure.include=*
endpoints.metrics.id=springmetrics
endpoints.metrics.sensitive=false
endpoints.metrics.enabled=true
endpoints.sensitive=true
endpoints.info.sensitive=false

spring.thymeleaf.cache=true
#spring.resources.cache-period=500
spring.resources.chain.html-application-cache=true

spring.resources.chain.enabled=true
spring.resources.chain.strategy.content.enabled=true
spring.resources.chain.strategy.content.paths=/**

file.upload.operations=/home/ubuntu/uploads

#Ifsc api token
ifsc.api.url=https://sky.yesbank.in:444/app/live/GetIFSCdetails/json/IFSCdetails
ifsc.api.clientid=ac2bdbd4-eefd-480b-ac15-bdcc496e9279
ifsc.api.client.secret=L8lN0sR7jR1fT0bF3xM5jS2dG0qF5mT4sN4mV4pU3qI2oO7bA0
ifsc.api.username=10080824
ifsc.api.password=KVOJ37cwnm
ifsc.api.version=1

remit.partner.code=FYNTE
remit.me.refno=ESB0007

upi.api.url=https://sky.yesbank.in:444/app/live/UPIRemitServices

send.remitt.url=https://sky.yesbank.in:444/app/live/InwardRemittanceByPartnerService2SSL

yesbank.tran.statuscheck.cron.expression=0 0/30 0-23 ? * *
yesbank.tran.statuscheck.cron.expression.completed=0 0/30 0-23 ? * *
yesbank.penny.statuscheck.cron.expression.completed=0 0/30 0-23 ? * *
guaranted.rate.applicable.cron.expression=0 0/30 0-23 ? * *
transaction.staging.state.longer.duration.cron.expression=0 0/30 0-23 ? * *

guaranted.rate.time.limit.minutes=2880
txn.cancellation.time.limit.minutes=7200

spring.mail.protocol=smtp
spring.mail.host=email-smtp.ap-southeast-2.amazonaws.com
spring.mail.port=587
spring.mail.username=AKIARBVBOP7ZPRBQYRF3
spring.mail.password=BAxaPiw4YUIgNaVYbuaNEZjmXEBP7hIQB2U/+Q7G+PJp
spring.mail.fromEmail=XDC Payments Support <help@xdcforpayments.org>

app.mail.protocol=smtp
app.mail.host=email-smtp.ap-southeast-2.amazonaws.com
app.mail.port=587
app.mail.username=AKIARBVBOP7ZPRBQYRF3
app.mail.password=BAxaPiw4YUIgNaVYbuaNEZjmXEBP7hIQB2U/+Q7G+PJp
app.mail.fromEmail=XDC Payments Support <help@xdcforpayments.org>

app.mail.template.location=/home/ubuntu/uploads/message_templates/
app.mail.pdf.location=/home/ubuntu/uploads/attachments/
app.mail.pdf.template.location=/home/ubuntu/uploads/attachment_templates/

#Nepal City bank credentials
nepal.remitt.url=https://www.ct-xpress.net/SendWSV5_IBFT/txnservice.asmx
nepal.remitt.agentcode =FYNTE001
nepal.remitt.userid =API_FYNTE
nepal.remitt.apipassword =7f!0AqU$nVe3T

#Terrapay API details
terrapay.remitt.url=https://localhost:9001/api/terrapay/initiateTransfer
terrapay.status.url=https://localhost:9001/api/terrapay/getstatus
terrapay.uname=fynte_terrapay
terrapay.pword=Viral@2009
