CREATE TABLE "admin_currencies" (
    "id" int8 NOT NULL,
    "publish" bool DEFAULT true,
    "is_delete" bool DEFAULT false,
    "country_code" varchar(20) COLLATE "pg_catalog"."default",
    "country_name" varchar(255) COLLATE "pg_catalog"."default",
    "currency_name" varchar(255) COLLATE "pg_catalog"."default",
    "currency_code" varchar(255) COLLATE "pg_catalog"."default",
    "currency_description" varchar(255) COLLATE "pg_catalog"."default",
    "currency_symbol" varchar(255) COLLATE "pg_catalog"."default",
    CONSTRAINT admin_currencies_prikeys PRIMARY KEY (id)
);


INSERT INTO admin_currencies (id, country_name, currency_name, currency_code, currency_symbol,publish,country_code,is_delete) VALUES
 (1, 'Albania', 'Leke', 'ALL', 'Lek', 't','AL', 't'),
 (2, 'America', 'Dollars', 'USD', '$', 't','US', 't'),
 (3, 'Afghanistan', 'Afghanis', 'AF', '؋','t','AF', 't'),
 (4, 'Argentina', 'Pesos', 'ARS', '$', 't','AR', 't'),
 (5, 'Aruba', 'Guilders', 'AWG', 'ƒ', 't','AW', 't'),
 (6, 'Australia', 'Dollars', 'AUD', '$', 't','AU', 'f'),
 (7, 'Azerbaijan', 'New Manats', 'AZ', 'ман', 't','AZ', 't'),
 (8, 'Bahamas', 'Dollars', 'BSD', '$', 't','BS', 't'),
 (9, 'Barbados', 'Dollars', 'BBD', '$', 't','BB', 't'),
 (10, 'Belarus', 'Rubles', 'BYR', 'p.', 't','BY', 't'),
 (11, 'Belgium', 'Euro', 'EUR', '€', 't','BE', 't'),
 (12, 'Beliz', 'Dollars', 'BZD', 'BZ$', 't','BZ', 't'),
 (13, 'Bermuda', 'Dollars', 'BMD', '$', 't','BM', 't'),
 (14, 'Bolivia', 'Bolivianos', 'BOB', '$b', 't','BO', 't'),
 (15, 'Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM', 't','BA', 't'),
 (16, 'Botswana', 'Pula\s', 'BWP', 'P', 't','BW', 't'),
 (17, 'Bulgaria', 'Leva', 'BG', 'лв', 't','BG', 't'),
 (18, 'Brazil', 'Reais', 'BRL', 'R$', 't','BR', 't'),
 (19, 'Britain (United Kingdom)', 'Pounds', 'GBP', '£', 't','GB', 't'),
 (20, 'Brunei Darussalam', 'Dollars', 'BND', '$', 't','BN', 't'),
 (21, 'Cambodia', 'Riels', 'KHR', '៛','t','KH', 't'),
 (22, 'Canada', 'Dollars', 'CAD', '$', 't','CA', 'f'),
 (23, 'Cayman Islands', 'Dollars', 'KYD', '$', 't','KY', 't'),
 (24, 'Chile', 'Pesos', 'CLP', '$', 't','CL', 't'),
 (25, 'China', 'Yuan Renminbi', 'CNY', '¥', 't','CN', 't'),
 (26, 'Colombia', 'Pesos', 'COP', '$', 't','CO', 't'),
 (27, 'Costa Rica', 'Colón', 'CRC', '₡', 't','CR', 't'),
 (28, 'Croatia', 'Kuna', 'HRK', 'kn', 't','HR', 't'),
 (29, 'Cuba', 'Pesos', 'CUP', '₱', 't','CU', 't'),
 (30, 'Cyprus', 'Euro', 'EUR', '€', 't','CY', 't'),
 (31, 'Czech Republic', 'Koruny', 'CZK', 'Kč', 't','CZ', 't'),
 (32, 'Denmark', 'Kroner', 'DKK', 'kr', 't','DK', 't'),
 (33, 'Dominican Republic', 'Pesos', 'DOP ', 'RD$', 't','DO', 't'),
 (34, 'East Caribbean', 'Dollars', 'XCD', '$','t',',', 't'),
 (35, 'Egypt', 'Pounds', 'EGP', '£', 't','EG', 't'),
 (36, 'El Salvador', 'Colones', 'SVC', '$', 't','SV', 't'),
 (37, 'England (United Kingdom)', 'Pounds', 'GBP', '£', 't','GB', 't'),
 (38, 'Euro', 'Euro', 'EUR', '€', 't',',', 't'),
 (39, 'Falkland Islands', 'Pounds', 'FKP', '£', 't','FK', 't'),
 (40, 'Fiji', 'Dollars', 'FJD', '$', 't','FJ', 't'),
 (41, 'France', 'Euro', 'EUR', '€', 't','FR', 'f'),
 (132, 'Germany', 'Euro', 'EUR', '€', 't','DE', 'f'),
 (42, 'Ghana', 'Cedis', 'GHC', '¢', 't','GH', 't'),
 (43, 'Gibraltar', 'Pounds', 'GIP', '£', 't','GI', 't'),
 (44, 'Greece', 'Euro', 'EUR', '€', 't', 'GR', 't'),
 (45, 'Guatemala', 'Quetzales', 'GTQ', 'Q', 't','GT', 't'),
 (46, 'Guernsey', 'Pounds', 'GGP', '£', 't',',', 't'),
 (47, 'Guyana', 'Dollars', 'GYD', '$', 't','GY', 't'),
 (48, 'Holland (Netherlands)', 'Euro', 'EUR', '€', 't',',', 't'),
 (49, 'Honduras', 'Lempiras', 'HNL', 'L', 't','HN', 't'),
 (50, 'Hong Kong', 'Dollars', 'HKD', '$', 't','HK', 't'),
 (51, 'Hungary', 'Forint', 'HUF', 'Ft', 't','HU', 't'),
 (52, 'Iceland', 'Kronur', 'ISK', 'kr', 't','IS', 't'),
 (53, 'India', 'Rupees', 'INR', 'Rs', 't','IN', 'f'),
 (54, 'Indonesia', 'Rupiahs', 'IDR', 'Rp', 't','ID', 't'),
 (55, 'Iran', 'Rials', 'IRR', '﷼', 't','IR', 't'),
 (56, 'Ireland', 'Euro', 'EUR', '€', 't','IE', 't'),
 (57, 'Isle of Man', 'Pounds', 'IMP', '£', 't',',', 't'),
 (58, 'Israel', 'New Shekels', 'ILS', '₪', 't','IL', 't'),
 (59, 'Italy', 'Euro', 'EUR', '€', 't','IT', 'f'),
 (60, 'Jamaica', 'Dollars', 'JMD', 'J$', 't','JM', 't'),
 (61, 'Japan', 'Yen', 'JPY', '¥', 't','JP', 't'),
 (62, 'Jersey', 'Pounds', 'JEP', '£', 't',',', 't'),
 (63, 'Kazakhstan', 'Tenge', 'KZT', 'лв', 't','KZ', 't'),
 (64, 'Korea (North)', 'Won', 'KPW', '₩', 't','KP', 't'),
 (65, 'Korea (South)', 'Won', 'KRW', '₩', 't','KR', 't'),
 (66, 'Kyrgyzstan', 'Soms', 'KGS', 'лв', 't','KG', 't'),
 (67, 'Laos', 'Kips', 'LAK', '₭', 't',',', 't'),
 (68, 'Latvia', 'Lati', 'LVL', 'Ls','t','LV', 't'),
 (69, 'Lebanon', 'Pounds', 'LBP', '£', 't','LB', 't'),
 (70, 'Liberia', 'Dollars', 'LRD', '$', 't', 'LR', 't'),
 (71, 'Liechtenstein', 'Switzerland Francs', 'CHF', 'CHF', 't','LI', 'f'),
 (72, 'Lithuania', 'Litai', 'LTL', 'Lt', 't', 'LT', 't'),
 (73, 'Luxembourg', 'Euro', 'EUR', '€', 't','LU', 't'),
 (74, 'Macedonia', 'Denars', 'MKD', 'ден', 't','MK', 't'),
 (75, 'Malaysia', 'Ringgits', 'MYR', 'RM', 't','MY', 't'),
 (76, 'Malta', 'Euro', 'EUR', '€', 't','MT', 't'),
 (77, 'Mauritius', 'Rupees', 'MUR', '₨', 't','MU', 't'),
 (78, 'Mexico', 'Pesos', 'MX', '$', 't','MX', 't'),
 (79, 'Mongolia', 'Tugriks', 'MNT', '₮','t','MN', 't'),
 (80, 'Mozambique', 'Meticais', 'MZ', 'MT', 't','MZ', 't'),
 (81, 'Namibia', 'Dollars', 'NAD', '$', 't','NA', 't'),
 (82, 'Nepal', 'Rupees', 'NPR', '₨', 't', 'NP', 't'),
 (83, 'Netherlands Antilles', 'Guilders', 'ANG', 'ƒ', 't','AL', 't'),
 (84, 'Netherlands', 'Euro', 'EUR', '€', 't','NL', 'f'),
 (85, 'New Zealand', 'Dollars', 'NZD', '$', 't','NZ', 't'),
 (86, 'Nicaragua', 'Cordobas', 'NIO', 'C$', 't','NI', 't'),
 (87, 'Nigeria', 'Nairas', 'NG', '₦', 't','NG', 't'),
 (88, 'North Korea', 'Won', 'KPW', '₩', 't',',', 't'),
 (89, 'Norway', 'Krone', 'NOK', 'kr', 't','NO', 't'),
 (90, 'Oman', 'Rials', 'OMR', '﷼', 't','OM', 't'),
 (91, 'Pakistan', 'Rupees', 'PKR', '₨', 't','PK', 't'),
 (92, 'Panama', 'Balboa', 'PAB', 'B/.', 't','PA', 't'),
 (93, 'Paraguay', 'Guarani', 'PYG', 'Gs', 't','PY', 't'),
 (94, 'Peru', 'Nuevos Soles', 'PE', 'S/.', 't','PE', 't'),
 (95, 'Philippines', 'Pesos', 'PHP', 'Php', 't','PH', 't'),
 (96, 'Poland', 'Zlotych', 'PL', 'zł', 't','PL', 't'),
 (97, 'Qatar', 'Rials', 'QAR', '﷼', 't','QA', 't'),
 (98, 'Romania', 'New Lei', 'RO', 'lei', 't','RO', 't'),
 (99, 'Russia', 'Rubles', 'RUB', 'руб', 't','RU', 't'),
 (100, 'Saint Helena', 'Pounds', 'SHP', '£', 't','SH', 't'),
 (101, 'Saudi Arabia', 'Riyals', 'SAR', '﷼', 't','SA', 't'),
 (102, 'Serbia', 'Dinars', 'RSD', 'Дин.', 't','CS', 't'),
 (103, 'Seychelles', 'Rupees', 'SCR', '₨', 't','SC', 't'),
 (104, 'Singapore', 'Dollars', 'SGD', '$', 't','SG', 'f'),
 (105, 'Slovenia', 'Euro', 'EUR', '€', 't','SI', 't'),
 (106, 'Solomon Islands', 'Dollars', 'SBD', '$', 't','SB', 't'),
 (107, 'Somalia', 'Shillings', 'SOS', 'S', 't','SO', 't'),
 (108, 'South Africa', 'Rand', 'ZAR', 'R', 't','ZA', 't'),
 (109, 'South Korea', 'Won', 'KRW', '₩', 't',',', 't'),
 (110, 'Spain', 'Euro', 'EUR', '€','t','ES', 'f'),
 (111, 'Sri Lanka', 'Rupees', 'LKR', '₨', 't','LK', 't'),
 (112, 'Sweden', 'Kronor', 'SEK', 'kr', 't','SE', 't'),
 (113, 'Switzerland', 'Francs', 'CHF', 'CHF', 't','CH', 't'),
 (114, 'Suriname', 'Dollars', 'SRD', '$', 't','SR', 't'),
 (115, 'Syria', 'Pounds', 'SYP', '£', 't','SY', 't'),
 (116, 'Taiwan', 'New Dollars', 'TWD', 'NT$', 't','TW', 't'),
 (117, 'Thailand', 'Baht', 'THB', '฿', 't', 'TH', 't'),
 (118, 'Trinidad and Tobago', 'Dollars', 'TTD', 'TT$', 't','TT', 't'),
 (119, 'Turkey', 'Lira', 'TRY', 'TL','t','TR', 't'),
 (120, 'Turkey', 'Liras', 'TRL', '£', 't','TR', 't'),
 (121, 'Tuvalu', 'Dollars', 'TVD', '$', 't','TV', 't'),
 (122, 'Ukraine', 'Hryvnia', 'UAH', '₴', 't','UA', 't'),
 (123, 'United Kingdom', 'Pounds', 'GBP', '£', 't','GB', 'f'),
 (124, 'United States of America', 'Dollars', 'USD', '$', 't','US', 'f'),
 (125, 'Uruguay', 'Pesos', 'UYU', '$U', 't','UY', 't'),
 (126, 'Uzbekistan', 'Sums', 'UZS', 'лв', 't','UZ', 't'),
 (127, 'Vatican City', 'Euro', 'EUR', '€', 't','VA', 't'),
 (128, 'Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs', 't','VE', 't'),
 (129, 'Vietnam', 'Dong', 'VND', '₫', 't','VN', 't'),
 (130, 'Yemen', 'Rials', 'YER', '﷼', 't','YE', 't'),
 (131, 'Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$', 't','ZW', 't'),
 (133, 'United Arab Emirates', 'UAE Dirham', 'AED', 'د.إ', 't','ARE','f');