CREATE TABLE "street_type" (
  "id" int8 NOT NULL,
  "create_at" timestamp(6),
  "create_by" varchar(255) COLLATE "pg_catalog"."default",
  "is_delete" bool DEFAULT false,
  "publish" bool DEFAULT true,
  "update_at" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default",
  "country_code" varchar(255) COLLATE "pg_catalog"."default",
  "street_type_key" varchar(255) COLLATE "pg_catalog"."default",
  "street_type_name" varchar(255) COLLATE "pg_catalog"."default",
  "country_id" int8,
  CONSTRAINT street_type_pkey PRIMARY KEY (id)
);
ALTER TABLE "street_type" ADD CONSTRAINT "fkhng9ly84sx7wj3f20pu72ml22" FOREIGN KEY ("country_id") REFERENCES "admin_countries" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;


INSERT INTO street_type (id, country_code, country_id, street_type_name, street_type_key,publish,is_delete) VALUES
(1, 'AU', 13, 'ACCESS','ACCS', 't','f'),
(2, 'AU', 13, 'ALLEY','ALLY', 't','f'),
(3, 'AU', 13, 'ALLEYWAY','ALWY', 't','f'),
(4, 'AU', 13, 'AMBLE','AMBL', 't','f'),
(5, 'AU', 13, 'ANCHORAGE','ANCG', 't','f'),
(6, 'AU', 13, 'APPROACH','APP', 't','f'),
(7, 'AU', 13, 'ARCADE','ARC', 't','f'),
(8, 'AU', 13, 'ARTERY','ART', 't','f'),
(9, 'AU', 13, 'AVENUE','AVE', 't','f'),
(10, 'AU', 13, 'BASIN','BASN', 't','f'),
(11, 'AU', 13, 'BEACH','BCH', 't','f'),
(12, 'AU', 13, 'BEND','BDGE', 't','f'),
(13, 'AU', 13, 'BLOCK','BDWY', 't','f'),
(14, 'AU', 13, 'BOULEVARD','BEND', 't','f'),
(15, 'AU', 13, 'BRACE','BLK', 't','f'),
(16, 'AU', 13, 'BRAE','BRAE', 't','f'),
(17, 'AU', 13, 'BREAK','BRCE', 't','f'),
(18, 'AU', 13, 'BRIDGE','BRK', 't','f'),
(19, 'AU', 13, 'BROADWAY','BROW', 't','f'),
(20, 'AU', 13, 'BROW','BVD', 't','f'),
(21, 'AU', 13, 'BYPASS','BYPA', 't','f'),
(22, 'AU', 13, 'BYWAY','BYWY', 't','f'),
(23, 'AU', 13, 'CAUSEWAY','CAUS', 't','f'),
(24, 'AU', 13, 'CENTRE','CCT', 't','f'),
(25, 'AU', 13, 'CENTREWAY','CDS', 't','f'),
(26, 'AU', 13, 'CHASE','CH', 't','f'),
(27, 'AU', 13, 'CIRCLE','CIR', 't','f'),
(28, 'AU', 13, 'CIRCLET','CL', 't','f'),
(29, 'AU', 13, 'CIRCUIT','CLDE', 't','f'),
(30, 'AU', 13, 'CIRCUS','CLT', 't','f'),
(31, 'AU', 13, 'CLOSE','CMMN', 't','f'),
(32, 'AU', 13, 'COLONNADE','CNR', 't','f'),
(33, 'AU', 13, 'COMMON','CNWY', 't','f'),
(34, 'AU', 13, 'CONCOURSE','CON', 't','f'),
(35, 'AU', 13, 'COPSE','COVE', 't','f'),
(36, 'AU', 13, 'CORNER','COWY', 't','f'),
(37, 'AU', 13, 'CORSO','CPS', 't','f'),
(38, 'AU', 13, 'COURT','CRCS', 't','f'),
(39, 'AU', 13, 'COURTYARD','CRD', 't','f'),
(40, 'AU', 13, 'COVE','CRES', 't','f'),
(41, 'AU', 13, 'CRESCENT','CRSG', 't','f'),
(42, 'AU', 13, 'CREST','CRSS', 't','f'),
(43, 'AU', 13, 'CROSS','CRST', 't','f'),
(44, 'AU', 13, 'CROSSING','CSO', 't','f'),
(45, 'AU', 13, 'CROSSROAD','CT', 't','f'),
(46, 'AU', 13, 'CROSSWAY','CTR', 't','f'),
(47, 'AU', 13, 'CRUISEWAY','CTTG', 't','f'),
(48, 'AU', 13, 'CUL-DE-SAC','CTYD', 't','f'),
(49, 'AU', 13, 'CUTTING','CUWY', 't','f'),
(50, 'AU', 13, 'DALE','DALE', 't','f'),
(51, 'AU', 13, 'DELL','DELL', 't','f'),
(52, 'AU', 13, 'DEVIATION','DEVN', 't','f'),
(53, 'AU', 13, 'DIP','DIP', 't','f'),
(54, 'AU', 13, 'DISTRIBUTOR','DR', 't','f'),
(55, 'AU', 13, 'DRIVE','DRWY', 't','f'),
(56, 'AU', 13, 'DRIVEWAY','DSTR', 't','f'),
(57, 'AU', 13, 'EDGE','EDGE', 't','f'),
(58, 'AU', 13, 'ELBOW','ELB', 't','f'),
(59, 'AU', 13, 'END','END', 't','f'),
(60, 'AU', 13, 'ENTRANCE','ENT', 't','f'),
(61, 'AU', 13, 'ESPLANADE','ESP', 't','f'),
(62, 'AU', 13, 'ESTATE','EST', 't','f'),
(63, 'AU', 13, 'EXPRESSWAY','EXP', 't','f'),
(64, 'AU', 13, 'EXTENSION','EXTN', 't','f'),
(65, 'AU', 13, 'FAIRWAY','FAWY', 't','f'),
(66, 'AU', 13, 'FIRE TRACK','FITR', 't','f'),
(67, 'AU', 13, 'FIRETRAIL','FLAT', 't','f'),
(68, 'AU', 13, 'FLAT','FOLW', 't','f'),
(69, 'AU', 13, 'FOLLOW','FORM', 't','f'),
(70, 'AU', 13, 'FOOTWAY','FRNT', 't','f'),
(71, 'AU', 13, 'FORESHORE','FRTG', 't','f'),
(72, 'AU', 13, 'FORMATION','FSHR', 't','f'),
(73, 'AU', 13, 'FREEWAY','FTRK', 't','f'),
(74, 'AU', 13, 'FRONT','FTWY', 't','f'),
(75, 'AU', 13, 'FRONTAGE','FWY', 't','f'),
(76, 'AU', 13, 'GAP','GAP', 't','f'),
(77, 'AU', 13, 'GARDEN','GDN', 't','f'),
(78, 'AU', 13, 'GATE','GDNS', 't','f'),
(79, 'AU', 13, 'GARDENS','GLD', 't','f'),
(80, 'AU', 13, 'GATES','GLEN', 't','f'),
(81, 'AU', 13, 'GLADE','GLY', 't','f'),
(82, 'AU', 13, 'GLEN','GR', 't','f'),
(83, 'AU', 13, 'GRANGE','GRA', 't','f'),
(84, 'AU', 13, 'GREEN','GRN', 't','f'),
(85, 'AU', 13, 'GROUND','GRND', 't','f'),
(86, 'AU', 13, 'GROVE','GTE', 't','f'),
(87, 'AU', 13, 'GULLY','GTES', 't','f'),
(88, 'AU', 13, 'HEIGHTS','HILL', 't','f'),
(89, 'AU', 13, 'HIGHROAD','HRD', 't','f'),
(90, 'AU', 13, 'HIGHWAY','HTS', 't','f'),
(91, 'AU', 13, 'HILL','HWY', 't','f'),
(92, 'AU', 13, 'INTERCHANGE','INTG', 't','f'),
(93, 'AU', 13, 'INTERSECTION','INTN', 't','f'),
(94, 'AU', 13, 'JUNCTION','JNC', 't','f'),
(95, 'AU', 13, 'KEY','KEY', 't','f'),
(96, 'AU', 13, 'LANDING','LANE', 't','f'),
(97, 'AU', 13, 'LANE','LDG', 't','f'),
(98, 'AU', 13, 'LANEWAY','LEES', 't','f'),
(99, 'AU', 13, 'LEES','LINE', 't','f'),
(100, 'AU', 13, 'LINE','LINK', 't','f'),
(101, 'AU', 13, 'LINK','LKT', 't','f'),
(102, 'AU', 13, 'LITTLE','LNWY', 't','f'),
(103, 'AU', 13, 'LOOKOUT','LOOP', 't','f'),
(104, 'AU', 13, 'LOOP','LT', 't','f'),
(105, 'AU', 13, 'LOWER','LWR', 't','f'),
(106, 'AU', 13, 'MALL','MALL', 't','f'),
(107, 'AU', 13, 'MEANDER','MEW', 't','f'),
(108, 'AU', 13, 'MEW','MEWS', 't','f'),
(109, 'AU', 13, 'MEWS','MNDR', 't','f'),
(110, 'AU', 13, 'MOTORWAY','MT', 't','f'),
(111, 'AU', 13, 'MOUNT','MWY', 't','f'),
(112, 'AU', 13, 'NOOK','NOOK', 't','f'),
(113, 'AU', 13, 'OUTLOOK','OTLK', 't','f'),
(114, 'AU', 13, 'PARADE','PARK', 't','f'),
(115, 'AU', 13, 'PARKLANDS','PASS', 't','f'),
(116, 'AU', 13, 'PARKWAY','PATH', 't','f'),
(117, 'AU', 13, 'PART','PDE', 't','f'),
(118, 'AU', 13, 'PASS','PHWY', 't','f'),
(119, 'AU', 13, 'PATH','PIAZ', 't','f'),
(120, 'AU', 13, 'PATHWAY','PKLD', 't','f'),
(121, 'AU', 13, 'PIAZZA','PKT', 't','f'),
(122, 'AU', 13, 'PLACE','PKWY', 't','f'),
(123, 'AU', 13, 'PLATEAU','PL', 't','f'),
(124, 'AU', 13, 'PLAZA','PLAT', 't','f'),
(125, 'AU', 13, 'POCKET','PLZA', 't','f'),
(126, 'AU', 13, 'POINT','PNT', 't','f'),
(127, 'AU', 13, 'PORT','PORT', 't','f'),
(128, 'AU', 13, 'PROMENADE','PROM', 't','f'),
(129, 'AU', 13, 'QUAD','QDGL', 't','f'),
(130, 'AU', 13, 'QUADRANGLE','QDRT', 't','f'),
(131, 'AU', 13, 'QUADRANT','QUAD', 't','f'),
(132, 'AU', 13, 'QUAY','QY', 't','f'),
(133, 'AU', 13, 'QUAYS','QYS', 't','f'),
(134, 'AU', 13, 'RAMBLE','RAMP', 't','f'),
(135, 'AU', 13, 'RAMP','RCH', 't','f'),
(136, 'AU', 13, 'RANGE','RD', 't','f'),
(137, 'AU', 13, 'PARK','PART', 't','f'),
(138, 'AU', 13, 'REACH','RDGE', 't','f'),
(139, 'AU', 13, 'RESERVE','RDS', 't','f'),
(140, 'AU', 13, 'REST','RDSD', 't','f'),
(141, 'AU', 13, 'RETREAT','RDWY', 't','f'),
(142, 'AU', 13, 'RIDE','RES', 't','f'),
(143, 'AU', 13, 'RIDGE','REST', 't','f'),
(144, 'AU', 13, 'RIDGEWAY','RGWY', 't','f'),
(145, 'AU', 13, 'RIGHT OF WAY','RIDE', 't','f'),
(146, 'AU', 13, 'RING','RING', 't','f'),
(147, 'AU', 13, 'RISE','RISE', 't','f'),
(148, 'AU', 13, 'RIVER','RMBL', 't','f'),
(149, 'AU', 13, 'RIVERWAY','RND', 't','f'),
(150, 'AU', 13, 'RIVIERA','RNDE', 't','f'),
(151, 'AU', 13, 'ROAD','RNGE', 't','f'),
(152, 'AU', 13, 'ROADS','ROW', 't','f'),
(153, 'AU', 13, 'ROADSIDE','ROWY', 't','f'),
(154, 'AU', 13, 'ROADWAY','RSBL', 't','f'),
(155, 'AU', 13, 'RONDE','RTE', 't','f'),
(156, 'AU', 13, 'ROSEBOWL','RTT', 't','f'),
(157, 'AU', 13, 'ROTARY','RTY', 't','f'),
(158, 'AU', 13, 'ROUND','RUE', 't','f'),
(159, 'AU', 13, 'ROUTE','RUN', 't','f'),
(160, 'AU', 13, 'ROW','RVR', 't','f'),
(161, 'AU', 13, 'RUE','RVRA', 't','f'),
(162, 'AU', 13, 'RUN','RVWY', 't','f'),
(163, 'AU', 13, 'SERVICE WAY','SBWY', 't','f'),
(164, 'AU', 13, 'SIDING','SDNG', 't','f'),
(165, 'AU', 13, 'SLOPE','SHWY', 't','f'),
(166, 'AU', 13, 'SOUND','SLPE', 't','f'),
(167, 'AU', 13, 'SPUR','SND', 't','f'),
(168, 'AU', 13, 'SQUARE','SPUR', 't','f'),
(169, 'AU', 13, 'STAIRS','SQ', 't','f'),
(170, 'AU', 13, 'STATE HIGHWAY','ST', 't','f'),
(171, 'AU', 13, 'STEPS','STPS', 't','f'),
(172, 'AU', 13, 'STRAND','STRA', 't','f'),
(173, 'AU', 13, 'STREET','STRP', 't','f'),
(174, 'AU', 13, 'STRIP','STRS', 't','f'),
(175, 'AU', 13, 'SUBWAY','SBWY', 't','f'),
(176, 'AU', 13, 'TARN','TARN', 't','f'),
(177, 'AU', 13, 'TERRACE','TCE', 't','f'),
(178, 'AU', 13, 'THOROUGHFARE','THOR', 't','f'),
(179, 'AU', 13, 'TOLLWAY','TKWY', 't','f'),
(180, 'AU', 13, 'TOP','TLWY', 't','f'),
(181, 'AU', 13, 'TOR','TOP', 't','f'),
(182, 'AU', 13, 'TOWERS','TOR', 't','f'),
(183, 'AU', 13, 'TRACK','TRI', 't','f'),
(184, 'AU', 13, 'TRAIL','TRK', 't','f'),
(185, 'AU', 13, 'TRAILER','TRL', 't','f'),
(186, 'AU', 13, 'TRIANGLE','TURN', 't','f'),
(187, 'AU', 13, 'TURN','TWRS', 't','f'),
(188, 'AU', 13, 'UNDERPASS','UPAS', 't','f'),
(189, 'AU', 13, 'UPPER','UPR', 't','f'),
(190, 'AU', 13, 'VALE','VALE', 't','f'),
(191, 'AU', 13, 'VIADUCT','VDCT', 't','f'),
(192, 'AU', 13, 'VIEW','VIEW', 't','f'),
(193, 'AU', 13, 'VILLAS','VLLS', 't','f'),
(194, 'AU', 13, 'VISTA','VSTA', 't','f'),
(195, 'AU', 13, 'WADE','WADE', 't','f'),
(196, 'AU', 13, 'WALK','WALK', 't','f'),
(197, 'AU', 13, 'WALKWAY','WAY', 't','f'),
(198, 'AU', 13, 'WAY','WHRF', 't','f'),
(199, 'AU', 13, 'WHARF','WKWY', 't','f'),
(200, 'AU', 13, 'WYND','WYND', 't','f'),
(201, 'AU', 13, 'YARD','YARD', 't','f');
























