package com.adminremit.masters.enums;

public enum ComplianceStatus {
    IP_NOT_FOUND,
    HIGH_RISK_COUNTRY_OK,
    HIGH_RISK_COUNTRY_NOK,
    DOCUMENT_CHECK_OK,
    DOCUMENT_CHECK_NOK,
    PERSONAL_DETAILS_OK,
    PERSONAL_DETAILS_NOK,
    LOGIN_IP_OK,
    LOGIN_IP_NOK,
    LOGIN_FROM_COUNTRY_OK,
    LOGIN_FROM_COUNTRY_NOK,
    TRANSACTION_IP_OK,
    TRANSACTION_IP_NOK,
    KYC_EXPIRY_OK,
    KYC_EXPIRY_NOK,
    TRANSFER_LIMIT_OK,
    TRANSFER_LIMIT_NOK,
    KYC_DOCUMENT_NOK,
    KYC_DOCUMENT_OK,
    TRANSACTION_SENDING_COUNTRY_NOK,
    TRANSACTION_SENDING_COUNTRY_OK

}
